source 'https://rubygems.org'

gem 'rails', '4.1.4'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer',  platforms: :ruby
gem 'activeadmin', github: 'activeadmin'
gem 'devise', github: 'plataformatec/devise'
gem 'carrierwave'
gem 'rmagick'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'haml'